# Generated by Django 4.0.6 on 2023-04-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Course name')),
                ('description', models.CharField(max_length=255, verbose_name='Course description')),
                ('level', models.CharField(choices=[('L', 'LOW'), ('M', 'MIDDLE'), ('H', 'HIGH')], max_length=1, verbose_name='Course level')),
                ('stu_num', models.IntegerField(default=0, verbose_name='Number of students of the course')),
                ('duration', models.IntegerField(default=0, verbose_name='Course duration')),
                ('fav_num', models.IntegerField(default=0, verbose_name='Number of favorite of the course')),
                ('view_num', models.IntegerField(default=0, verbose_name='Number of views of the course')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Course category')),
                ('course_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Course note')),
                ('teacher_comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Teacher comment')),
                ('detail', models.TextField(verbose_name='Course detail')),
                ('image', models.ImageField(default='default.jpg', upload_to='courses/%Y/%m', verbose_name='Cover of the course')),
                ('tag', models.CharField(blank=True, max_length=50, null=True, verbose_name='Course tag')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
    ]
