# Generated by Django 4.0.6 on 2023-04-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_chapter_section_courseresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='chapter duration'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=30, verbose_name='chapter name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='course category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='course note'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=255, verbose_name='course description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Course duration'),
        ),
        migrations.AlterField(
            model_name='course',
            name='fav_num',
            field=models.PositiveIntegerField(default=0, verbose_name='number of favorite of the course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='courses/%Y/%m', verbose_name='cover of the course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('L', 'LOW'), ('M', 'MIDDLE'), ('H', 'HIGH')], max_length=1, verbose_name='course level'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name='course name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='stu_num',
            field=models.PositiveIntegerField(default=0, verbose_name='number of students of the course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='course tag'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='teacher comment'),
        ),
        migrations.AlterField(
            model_name='course',
            name='view_num',
            field=models.PositiveIntegerField(default=0, verbose_name='number of views of the course'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='file',
            field=models.FileField(upload_to='courses/resources/%Y/%m', verbose_name='resource file'),
        ),
        migrations.AlterField(
            model_name='section',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='section duration'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=30, verbose_name='section name'),
        ),
    ]
