# Generated by Django 4.0.6 on 2023-04-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_chapter_duration_alter_chapter_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='cover_img',
            field=models.ImageField(default='default.jpeg', upload_to='courses/%Y/%m', verbose_name='cover of the course'),
        ),
    ]
