# Generated by Django 4.0.6 on 2023-04-19 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_remove_org_image_remove_teacher_image_org_avatar_and_more'),
        ('courses', '0004_remove_course_image_course_cover_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='organizations.teacher'),
            preserve_default=False,
        ),
    ]
