# Generated by Django 4.0.6 on 2023-04-20 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_remove_teacher_is_certified_remove_teacher_is_gold_and_more'),
        ('courses', '0005_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='org',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='organizations.org'),
            preserve_default=False,
        ),
    ]
