# Generated by Django 4.0.6 on 2023-05-10 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_chapter_is_deleted_alter_course_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='org',
        ),
    ]
