# Generated by Django 4.0.6 on 2023-05-21 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_tag_remove_course_tag_coursetag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursetag',
            unique_together={('course', 'tag')},
        ),
    ]
