# Generated by Django 4.0.6 on 2023-04-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfavorite',
            options={'verbose_name': 'user favorite', 'verbose_name_plural': 'user favorites'},
        ),
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': 'user message', 'verbose_name_plural': 'user messages'},
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_id',
            field=models.PositiveIntegerField(),
        ),
    ]
