# Generated by Django 4.0.6 on 2023-04-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_remove_org_image_remove_teacher_image_org_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_certified',
            field=models.BooleanField(default=False, verbose_name='certified organization'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_gold',
            field=models.BooleanField(default=False, verbose_name='gold organization'),
        ),
    ]
