# Generated by Django 4.0.6 on 2023-04-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_teacher_is_certified_teacher_is_gold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_certified',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_gold',
        ),
        migrations.AddField(
            model_name='org',
            name='is_certified',
            field=models.BooleanField(default=False, verbose_name='certified organization'),
        ),
        migrations.AddField(
            model_name='org',
            name='is_gold',
            field=models.BooleanField(default=False, verbose_name='gold organization'),
        ),
    ]
