# Generated by Django 4.0.6 on 2023-04-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_remove_teacher_is_certified_remove_teacher_is_gold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='fav_num',
            field=models.PositiveIntegerField(default=0, verbose_name='number of favorite of the organization'),
        ),
        migrations.AlterField(
            model_name='org',
            name='view_num',
            field=models.PositiveIntegerField(default=0, verbose_name='number of views of the organization'),
        ),
    ]
