# Generated by Django 4.0.6 on 2023-04-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_org_fav_num_alter_org_view_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='org',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
    ]
