# Generated by Django 4.0.6 on 2023-05-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_city_is_deleted_alter_org_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='fav_num',
            field=models.PositiveIntegerField(default=0, verbose_name='number of favorite of the teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='view_num',
            field=models.PositiveIntegerField(default=0, verbose_name='number of views of the teacher'),
        ),
    ]
